plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\newis\\OneDrive\\Desktop\\master_folder\\WORKFROMHOME\\THE MISSION\\ZAPHENATH\\KOUM\\koum-platform"
publishOrigin = "config"
commandOrigin = "ui"
base = "C:\\Users\\newis\\OneDrive\\Desktop\\master_folder\\WORKFROMHOME\\THE MISSION\\ZAPHENATH\\KOUM\\koum-platform"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]